modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayTest = "IGNORE_ALL_VERSION"
logoFile = "icon.png"
description = '''${mod_description}'''

[[mixins]]
config = "nopause.mixins.json"

[[dependencies.nopause]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.nopause]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "CLIENT"
